### PR TITLE
[node] Fix BigInt transformation

### LINKED ISSUE #73: [node] fix BigInt transformation when column value is null
In objectTypeToModelAttributes we defined a custom getter and setter to transform column value to / from BigInt.

But it didn't handle null well.

### PR DESCRIPTION
**Pull request by jiqiang90**
Close #73

### CODE REVIEW

File: packages/node/src/utils/graphql.ts [hunk 1]
```diff
@@ -34,10 +34,14 @@ export function objectTypeToModelAttributes(
     };
     if (type.toString() === 'BigInt') {
       columnOption.get = function () {
-        return BigInt(this.getDataValue(k));
+        if (this.getDataValue(k)) {
```
Comment (ianhe8x) [inline packages/node/src/utils/graphql.ts:37]: assign the result to a variable

**Review by ianhe8x — CHANGES_REQUESTED** [review]

**Review by ianhe8x — APPROVED** [review]
